<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDezUqs7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDezUqs7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDezUqs7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDezUqs7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDezUqs7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DezUqs7',
    'container.build_id' => '498ee73b',
    'container.build_time' => 1570968269,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDezUqs7');
